"""Add question explanation

Revision ID: 20ddbe7eb01a
Revises: 6d251d294b5c
Create Date: 2026-04-05 11:54:43.694811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20ddbe7eb01a'
down_revision: Union[str, Sequence[str], None] = '6d251d294b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'explanation')
    # ### end Alembic commands ###
