"""Add scheduled_for to Exam

Revision ID: 6d251d294b5c
Revises: 77911783c72e
Create Date: 2026-04-05 11:27:31.000435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d251d294b5c'
down_revision: Union[str, Sequence[str], None] = '77911783c72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'scheduled_for')
    # ### end Alembic commands ###
