"""Add created_at timestamps

Revision ID: 77911783c72e
Revises: 003_exam_title_topics_duration
Create Date: 2026-04-05 11:21:11.058361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77911783c72e'
down_revision: Union[str, Sequence[str], None] = '003_exam_title_topics_duration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidate_answer_exam_attempt_id_fkey'), 'candidate_answer', type_='foreignkey')
    op.drop_constraint(op.f('candidate_answer_question_id_fkey'), 'candidate_answer', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'candidate_answer', 'exam_attempt', ['exam_attempt_id'], ['id'])
    op.add_column('exam', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exam_attempt', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('exam_attempt_exam_id_fkey'), 'exam_attempt', type_='foreignkey')
    op.drop_constraint(op.f('exam_attempt_candidate_id_fkey'), 'exam_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attempt', 'candidate', ['candidate_id'], ['id'])
    op.create_foreign_key(None, 'exam_attempt', 'exam', ['exam_id'], ['id'])
    op.drop_constraint(op.f('question_exam_id_fkey'), 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(op.f('question_exam_id_fkey'), 'question', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exam_attempt', type_='foreignkey')
    op.drop_constraint(None, 'exam_attempt', type_='foreignkey')
    op.create_foreign_key(op.f('exam_attempt_candidate_id_fkey'), 'exam_attempt', 'candidate', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('exam_attempt_exam_id_fkey'), 'exam_attempt', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exam_attempt', 'created_at')
    op.drop_column('exam', 'created_at')
    op.drop_constraint(None, 'candidate_answer', type_='foreignkey')
    op.drop_constraint(None, 'candidate_answer', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_answer_question_id_fkey'), 'candidate_answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('candidate_answer_exam_attempt_id_fkey'), 'candidate_answer', 'exam_attempt', ['exam_attempt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
